# Generated by Django 3.1.7 on 2021-03-29 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0004_job_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Department',
        ),
    ]
