# Generated by Django 3.1.7 on 2021-04-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0006_auto_20210331_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ci',
            field=models.IntegerField(unique=True, verbose_name='cedula'),
        ),
    ]
