# Generated by Django 3.1.7 on 2021-04-09 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'sucursal', 'verbose_name_plural': 'sucursales'},
        ),
    ]
