# Generated by Django 3.1.7 on 2021-03-25 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210322_1042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalMeasureUnit',
        ),
    ]
